# Generated by Django 2.1.5 on 2020-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender_pref',
            field=models.CharField(blank=True, choices=[('Males', 'Males'), ('Females', 'Females'), ('Both', 'Both')], max_length=10, null=True, verbose_name='Show me'),
        ),
    ]
