# Generated by Django 2.1.5 on 2020-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_gender_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_pref',
            field=models.CharField(choices=[('Males', 'Males'), ('Females', 'Females'), ('Both', 'Both')], max_length=10, verbose_name='Show me'),
        ),
    ]
