# Generated by Django 2.1.5 on 2020-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200524_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_pref',
            field=models.CharField(choices=[('Males', 'Males'), ('Females', 'Females'), ('Both', 'Both')], default='Unspecified', max_length=10, verbose_name='Show me'),
        ),
    ]
