# Generated by Django 2.1.5 on 2020-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200531_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', height_field=500, upload_to='media', width_field=500),
        ),
    ]
